### ISSUE TITLE
Jan 2021 Roadmap Brainstorming 

### ISSUE THREAD

**Issue by fmrico** [IntelligentRoboticsLabs/ros2_planning_system#74]
Hi all,

I would like to have a list of desired features for the next weeks. Please, put in your threads your thoughts, and I can add them to this list:

- [ ] **Actions performers in Python (former #3)**
  It would be cool to implement the actions in Python (or even more languages). For this, we should implements `plansys::ActionExecutorClient` as a Python Class. 
- [ ] **rqt_gui plugin for visualize plan execution.**
  We could add a plugin for rqt_grap to visualize the execution of a plan. This could be implemented in the same way as I did [here](https://github.com/fmrico/ros2_knowledge_graph/tree/master/ros2_knowledge_graph_plugins), showing the action performers, each one as an ellipse with the action performer, filled with a color indicating if it ready, committed, or executing. In the arc, we could show the action currently executing, updated with the feedback info. Any better display will be acceptable, as well.
- [ ] **To integrate more pddl plan solvers.**
  As [POPF](https://github.com/IntelligentRoboticsLabs/ros2_planning_system/tree/master/plansys2_popf_plan_solver) and [TFD](https://github.com/IntelligentRoboticsLabs/plansys2_tfd_plan_solver), we could add more pddl plan solvers. We could check the [ICAPS IPC](https://www.icaps-conference.org/competitions/) and try to add the winners.
- [ ] **Package with many PDDL domains and problems to test if correctly executes**
- [ ] **To create a PlanSys2 Project in Guthub instead of being under IntelligentRoboticsLabs**
- [ ] **More tutorials and videos on the Web Page**
- [ ] **Merchandising!!**

Please, add more, comment on them, propose a solution, or whatever :smiley:
